### ISSUE TITLE
Hover results can be undefined

### ISSUE THREAD

**Issue by philippotto** [flowtype/flow-language-server#51]
According to the spec, hover requests should be answered with a non-optional contents attribute in the form of `contents: MarkedString | MarkedString[];`. However, flow-language-server returns undefined, if no hover is available. This should be an empty array instead to comply with the [spec](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover).

**Comment by wbinnssmith** [comment]
Thanks for reporting this @philippotto!
