### ISSUE TITLE
CompletionOptions.triggerCharacters include '.'

### ISSUE THREAD

**Issue by philippotto** [flowtype/flow-language-server#52]
According to the spec `triggerCharacters` should be a list of characters which automatically triggers autocompletion. I think for JavaScript this should include '.' so that autocompletions are queried for member access.

**Comment by wbinnssmith** [comment]
Thanks so much for reporting these issues @philippotto! It's awesome that you're integrating this with [Sublime's LSP](https://github.com/tomv564/LSP) client. 

Let me know if there's anything else I can do to help you. It would be awesome if you could send a PR to [this repo's README's Editor Integrations section](https://github.com/flowtype/flow-language-server#editor-integrations) with installation steps 😊
