### ISSUE TITLE
Document which parts of the language-server specifications are implemented

### ISSUE THREAD

**Issue by entropitor** [flowtype/flow-language-server#57]
Can we find somewhere which parts of the language-server specification are implemented?

**Comment by entropitor** [comment]
@wbinnssmith I'm a big fan of this library but I'd be nice if we knew what's missing and what should be working. 

And maybe how we can contribute to add the missing part to the library.

**Comment by wbinnssmith** [comment]
Completely agree. This is on my to-do list for sure. 

Functionality is more or less split into [the module files in the source](https://github.com/flowtype/flow-language-server/tree/master/src). If someone wants to send a PR to the readme it would be greatly appreciated. Would make for a straightforward contribution :)

**Comment by dcosson** [comment]
It would also be helpful to document a bit about the goals of the project. Like, of the things not implemented (renaming, formatting, etc), is it just a matter of not having gotten to it yet or have there been specific decisions made not to support it?

These features may have little to do with the flow type checker, but at the same time it would be convenient to be able to run a single language server that implements the entire protocol that I can point my editor LSP client plugin at.
