### ISSUE TITLE
lspHover is not resolved

### ISSUE THREAD

**Issue by TrySound** [flowtype/flow-language-server#59]
I use [vim-lsp](https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Flow) and have autocompletion, document symbols and go to definition commands. But hover doesn't work (I saw it in the code). When I call lspHover command I got `Retrieving hover...`

Not sure where to post it. I started here.

Here is vim-lsp log
```js
Thu Dec 14 12:24:02 2017:["s:on_text_document_did_save()", 4]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "server already started"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"hoverProvider": true, "documentSymbolProvider": true, "definitionProvider": true, "textDocumentSync": 2, "completionProvider": {"resolveProvider": true, "triggerCharacters": ["."]}}}}, "server_name": "flow-language-server"}, "message": "lsp server already initialized"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"path": ".../src/example.js", "__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "already opened"}}]
Thu Dec 14 12:24:11 2017:[{"response": {"data": {"path": ".../src/example.js", "__data__": "vim-lsp", "server_name": "flow-language-server"}, "message": "not dirty"}}]
Thu Dec 14 12:24:11 2017:["--->", 2, "flow-language-server", {"method": "textDocument/hover", "on_notification": "---funcref---", "params": {"textDocument": {"uri": ".../src/example.js"}, "position": {"character": 11, "line": 205}}}]
Thu Dec 14 12:24:11 2017:["<---", 2, "flow-language-server", {"response": {"id": 16, "jsonrpc": "2.0", "result": {"range": {"end": {"character": 14, "line": 205}, "start": {"character": 4, "line": 205}}, "contents": {"language": "javascript", "value": "...code..."}}}, "request": {"method": "textDocument/hover", "jsonrpc": "2.0", "id": 16, "params": {"textDocument": {"uri": ".../src/example.js"}, "position": {"character": 11, "line": 205}}}}]
Thu Dec 14 12:24:11 2017:["s:on_stdout client request on_notification() error", "Vim(call):E714: List required"]
```

**Comment by wbinnssmith** [comment]
hi @trysound!

hmm I just tried this out with a project and everything seems to work fine. Running `:LspHover` properly returns the type information for the symbol under the cursor.

From your log it looks like you're getting a valid response. Did you replace a lengthy response with that `...code...`?

`Retreiving hover...` looks like a response from `vim-lsp` rather than from the language server.

Can you use other flow lsp functionality in this project? Can you try running :LspHover on another project?

cc @prabirshrestha who may have some insight

**Comment by prabirshrestha** [comment]
Based on this log could be a bug in vim-lsp where it isn’t handling the response correctly.

@trysound can you try pulling the latest vim-lsp and give it a try. Yesterday I merged a change related to hover so the bug might have already been fixed.

**Comment by TrySound** [comment]
Yay! It works. Thanks
