### ISSUE TITLE
Provide more info with autocomplete

### ISSUE THREAD

**Issue by TrySound** [flowtype/flow-language-server#60]
Right now I see only `function` and `variable` types and in some (don't really now which ones) cases class type. It is better than vim-flow but I believe flow provide more types.

Language server allows to specify whole rainbow of types.
https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L731-L757

I could send a PR but don't know what is the output of flow.

**Comment by rcjsuen** [comment]
I did some investigating and found where Flow's output is converted to an LSP type.

https://github.com/flowtype/flow-language-server/blob/daa83c3bc5d6323f0e1ce17bfd38c04ad43f52b9/packages/flow-language-server/src/Completion.js#L148-L158

From my tests, it seems like the Flow server doesn't provide enough information for the language server to use. Consider the following class:
```JavaScript
// @flow

class MyClass {
  myProperty: boolean;
  constructor(param: number) {
  }

  method(value: string): number {
    this.myProp // <- invoke code completion here
    return 0;
  }
}
```
We get the output below from Flow. Note that nothing in the returned JSON indicates that the item is a "field" or a "property".
https://github.com/flowtype/flow-language-server/blob/daa83c3bc5d6323f0e1ce17bfd38c04ad43f52b9/packages/flow-language-server/src/Completion.js#L77-L83
```JavaScript
{
  "isIncomplete": false,
  "items": [
    {
      "description": "boolean",
      "displayText": "myProperty",
      "replacementPrefix": "myProp",
      "rightLabel": "boolean",
      "text": "myProperty"
    }
  ]
}
```
The above JSON result from the Flow server gets converted into the following JSON response by the language server. Its `kind` of `6` indicates that it is a `CompletionItemKind.Variable`. Given the code at the top of this comment as well as the JSON result from the Flow server, we can see why the language server would conclude that this item is a "variable".
```JavaScript
{
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "isIncomplete": false,
    "items": [
      {
        "label": "myProperty",
        "kind": 6,
        "documentation": "boolean",
        "detail": "boolean"
      }
    ]
  }
}
```

**Comment by TrySound** [comment]
It's not relevant since this commit.
https://github.com/facebook/flow/commit/c5d21c66a57bd106cf0ce973112dff62d73f1672
