### ISSUE TITLE
using `:grep ` with this running

### ISSUE THREAD

**Issue by iamdustan** [flowtype/flow-language-server#63]
I experience this terribly frustrating behavior where this constantly wipes out my `:grep ` quick jump window. I may just lack the vimfu necessary to avoid this so I’m crying out for help 😇 

(Since I am lacking the words to describe the issue any better than that)

**Comment by hansonw** [comment]
This seems like more of an issue with the vim LSP client? (Assuming you're using https://github.com/autozimu/LanguageClient-neovim)?

**Comment by iamdustan** [comment]
Yeaaah probably (thanks for the super-speedy response). Do you have another recommendation? I’ve copied my setup pretty much from https://github.com/flowtype/flow-language-server#neovim.

**Comment by iamdustan** [comment]
Configuration change saves the day! Thanks for pointing me in the right direction, @hansonw.

```
:help LanguageClient
2.8 g:LanguageClient_diagnosticsList        g:LanguageClient_diagnosticsList

List used to fill diagnostic messages.

Default: "quickfix"
Valid options: "quickfix" | "location" | ""
```
