### ISSUE TITLE
Add code actions

### ISSUE THREAD

**Issue by slonoed** [flowtype/flow-language-server#77]
I'm thinking to implement `codeActions` and `executeCommand` and provide some AST based transformations, like convert function to arrow function. 

My idea is to separate refactoring from language server itself. It could be done in this repo, or via plugins as it works in [javascript-typescript-langserver][jtl]. I like the idea of plugins because it allows me to publish changes easily. However requires some effort to implement a plugin system, which should be more general for future usage.

I already have simple prototype which uses [babylon][babylon] to parse code and [vim-lsc plugin][lsc] for vim.

![ezgif-5-d1ad38801d](https://user-images.githubusercontent.com/463239/39893967-c1deaea4-54a5-11e8-8a21-adba0a22b34f.gif)

What do you think?

### Similar tooling
[js-refactor][js-refactor] —  works only in VSCode

[js-refactor]: https://github.com/cmstead/js-refactor/blob/master/package.json
[babylon]: https://github.com/babel/babel/tree/master/packages/babylon
[lsc]: https://github.com/natebosch/vim-lsc
[jtl]: https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/src/plugins.ts

**Comment by hansonw** [comment]
Why not have a standalone language server for the AST transformations? It's
not super high overhead, and I'm not sure that there's a lot to share with
the Flow server anyway.

On Thu, May 10, 2018 at 2:10 PM, Dmitry Manannikov <notifications@github.com

**Comment by slonoed** [comment]
@hansonw it was my initial idea. Just wanted to check in case someone already has this plan.

I think the main benefit from one package it is, well, one package. Most language clients don't support multiple language servers.

**Comment by hansonw** [comment]
Atom/VSCode certainly support multiple servers per filetype.. I'm not sure about vim, though.
